### ISSUE TITLE
Multiple database connections from single project

### ISSUE THREAD

**Issue by travisvn** [travisvn/supabase-pause-prevention#3]
In order to maximize backwards compatibility and keep older projects afloat, it would be advantageous to leverage a single project to connect to multiple Supabase databases / projects. 

This might best be accomplished through usage of Cloudflare Workers or similar. It might also require splintering of cloud function calls, as the CPU usage in terms of execution time might be high when switching between database connections. 

However, this would greatly aid in helping keep older projects from being paused, as Vercel seems to love playing with their caching functionality in ways that can create a bit of a headache. 

Feel free to comment with suggestions

**Comment by jt6677** [comment]
I was thinking about this same  cron job loop hole Supabase created themselves.

**Comment by travisvn** [comment]
I actually ended up creating a whole new project to solve this problem

https://github.com/travisvn/supabase-inactive-fix
